# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: imagecrypt
version: '0.0.0'
github: "githubuser/imagecrypt"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: imagecrypt is a new Haskeleton package.
# category: Other

extra-source-files:
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

executables:
  imagecrypt:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - JuicyPixels
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

