#!/bin/bash

cat README.md | grep -Pzo '(?s).*## Scoreboard.*- \|.[^\n]*.[^\n]*'
echo

echo -n $'| Haskell (golfed)             | '
echo -n "$(echo "$(cat hs2/*.hs | wc -c)-$(find hs2/*.hs | wc -l)" | bc)"
echo ' bytes            |'

echo -n $'| Javascript (node, golfed)    | '
echo -n "$(echo "$(cat js/*.js | wc -c)-$(find js/*.js | wc -l)" | bc)"
echo ' bytes            |'

echo -n $'| Javascript (browser, golfed) | '
echo -n "$(echo "$(cat js2/*.js | wc -c)-$(find js2/*.js | wc -l)" | bc)"
echo ' bytes            |'

echo -n $'| Vim                          | '
echo -n "$(echo "$(cat vim/enc vim/dec | sed 's/<[^>]*>/a/g' | wc -c)-$(find vim/* | wc -l)" | bc)"
echo ' keypresses       |'
